<?php defined('APPLICATION') or die;
echo $this->Form->Open();
echo $this->Form->Errors();
$Alsoname = trim($this->data('Alsoname'));
$DefaultTopic = $this->data('DefaultTopic');
$DiscussionTitle = $this->data('DiscussionName');
if ($Alsoname == "") { 
	$Label = t('Enter new Topic');
} else {
	$Label = t('Current Topic');
}	

echo '<br><div Class="Topichead">'.$DiscussionTitle.'</div>';

echo '<ul><li Class="TopicNew">'.$this->Form->Label($Label.':','Alsoname');

echo $this->Form->TextBox('Alsoname',
								array('MultiLine' => false,
										'class' => 'TopicBox',
										'rows' => 1));
echo '<br>Note: To match deterministic topics you must enclose the topic with double quotes.<br>';
echo '<br>';
if ($DefaultTopic == '') {
	echo wrap('There is no auto-generated topic with the current settings and this discussion title.','div ');
} elseif ($DefaultTopic != $Alsoname) {
	echo wrap('Default (autogenerated) topic:<b>'.$DefaultTopic.'<//b>','div ');
} else {
	echo wrap('&nbsp','div ');
}
echo '<br>';
echo "</li></ul>";
echo '<div  >';
echo $this->Form->button(t('Save'));
if ($DefaultTopic != '') echo $this->Form->button(t('Generate'));
if ($Alsoname != "") echo $this->Form->button(t('Remove'));

echo $this->Form->button(t('Cancel')); 
echo '</div></div>';
?>
